### ISSUE TITLE
Output of reads used to assemble for each contig

### ISSUE THREAD

**Issue by yuyuleung** [liulab-dfci/TRUST4#281] opened 2024-06-19 03:25 UTC
Dear Dr. Li, 

Firstly, I would like to express my gratitude for creating such excellent tools.

Currently, I am going to try performing TRUST4 (bulk-mode) on my spatial-TCR data. However, I am wondering how I can access the reads used to assemble for each contig? Then I can analyze the spatial position from reads of each contig.

Thank you so much. 

Best wishes,
Yuyu

**Comment by mourisl** [comment] 2024-06-19 03:47
You can add the "--outputReadAssignment" option for that. It outputs the reads assignment to the assembled contigs during realignment stage, which might be different from the reads used in the assembly stage.

**Comment by yuyuleung** [comment] 2024-06-19 03:50
Thanks for the quick answer. 

Then, will the number of reads realigned to the contigs be less or more than the reads really used to assemble the conitg?

**Comment by mourisl** [comment] 2024-06-19 03:55
That depends. I think the longer contigs or the ones show up early in the final.out file will get more reads, and the shorter ones or in the tail of the final.out file will get less.

**Comment by yuyuleung** [comment] 2024-06-19 04:47
Thanks for the answer. 

One more question, I have tried adding the option "--outputReadAssignment" earlier but in the single-cell mode. The commond as following:

./run-trust4 \
        -u read2.fq.gz \
        -t 8 \
        --barcode read1.fq.gz \
        --readFormat bc:0:16 \
        --barcodeTranslate barcodeTranslate.tsv \
        -f genome_ref \
        --ref imgt_ref \
        --outputReadAssignment \
        -o test

However, the test_assign.out is empty. Is the option only designed for the bulk mode?

Thanks again.

**Comment by mourisl** [comment] 2024-06-19 04:50
It should output in single-cell mode too. Do you still have the running log from TRUST4?

**Comment by yuyuleung** [comment] 2024-06-19 04:57
I have this log. :)
[assemble01.log](https://github.com/user-attachments/files/15895594/assemble01.log)

**Comment by yuyuleung** [comment] 2024-06-19 04:58
I have not found a step using the option "--outputReadAssignment".

**Comment by mourisl** [comment] 2024-06-19 05:23
It's the option --readAssignment in the command "./annotator -f /./TRUST4/mouse/mouse_IMGT+C_tcr_1line.fa -a test_final.out -t 8 -o test --barcode --readAssignment test_assign.out --outputCDR3File --airrAlignment > test_annot.fa". This looks valid tome. I'll give this a try on my side on some data sets tomorrow.

**Comment by yuyuleung** [comment] 2024-06-19 05:59
Oh, yes I have found it too. But the test_assign.out is always empty. Thanks for checking it.

**Comment by yuyuleung** [comment] 2024-06-25 03:13
Dear Dr. Li,

Have you checked this issue and had some result already? Thanks. 

Best wishes,
Yuyu

**Comment by mourisl** [comment] 2024-06-25 19:28
Thank you for the reminder. I could not reproduce the error you found. Is it possible to share the final.out and assembled_reads.fa files?

**Comment by yuyuleung** [comment] 2024-06-26 01:39
Yes, I am sharing to you by Email. Thanks for the help. :)

Best wishes,
Yuyu

**Comment by yuyuleung** [comment] 2024-06-26 01:40
Yes, I am sharing them by Email with you. Thanks for the help. :)

Best wishes,
Yuyu

**Comment by mourisl** [comment] 2024-07-08 15:43
Thank you for sharing the files. The issue is resolved during the email communication. I'll close this thread.

**Closed by mourisl** 2024-07-08 15:43 UTC
